<?php

/**
 * @file
 * The Podcast module.
 */

/**
 * Implements hook_menu().
 */
function itkdev_podcast_menu() {
  return [
    // Add "Bibcast" item to main menu.
    'itkdev/podcast' => [
      'menu_name' => 'main-menu',
      'title' => 'Podcast',
      'weight' => 1000,
      'page callback' => 'itkdev_podcast_view',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    ],
    'itkdev/podcast/%' => [
      'page callback' => 'itkdev_podcast_view',
      'page arguments' => [2],
      'access callback' => TRUE,
    ],
  ];
}

/**
 * View for Podcast.
 */
function itkdev_podcast_view($path = NULL) {
  return [
    '#markup' => '<div id="itk-dev-podcast"></div>',
    '#attached' => [
      'css' => [
        drupal_get_path('module', 'itkdev_podcast') . '/apps/main/css/app.css',
      ],
      'js' => [
        drupal_get_path('module', 'itkdev_podcast') . '/apps/main/js/app.js',
      ],
    ],
  ];
}

/**
 * Implements hook_block_info().
 */
function itkdev_podcast_block_info() {
  $blocks['itkdev_podcast_frontpage'] = [
    'info' => t('Podcasts (frontpage)'),
    'cache' => DRUPAL_NO_CACHE,
  ];

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function itkdev_podcast_block_view($delta = '') {
  return [
    'subject' => NULL,
    'content' => [
      '#markup' => '<div id="itk-dev-podcast"></div>',
      '#attached' => [
        'css' => [
          drupal_get_path('module', 'itkdev_podcast') . '/apps/block/css/app.css',
        ],
        'js' => [
          drupal_get_path('module', 'itkdev_podcast') . '/apps/block/js/app.js',
        ],
      ],
    ],
  ];
}
