<?php

/**
 * @file
 * The Podcast module.
 */

/**
 * Implements hook_menu().
 */
function itkdev_podcast_menu() {
  return [
    // Add "Bibcast" item to main menu.
    'itkdev/podcast' => [
      'menu_name' => 'main-menu',
      'title' => 'Podcast',
      'weight' => 1000,
      'page callback' => 'itkdev_podcast_view',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    ],
    'itkdev/podcast/%' => [
      'page callback' => 'itkdev_podcast_view',
      'page arguments' => [2],
      'access callback' => TRUE,
    ],
  ];
}

/**
 * View for Podcast.
 */
function itkdev_podcast_view($action = NULL) {
  return [
    '#markup' => '<pre>' . json_encode([__METHOD__, $action], JSON_PRETTY_PRINT) . '</pre>',
  ];
}
